### ISSUE TITLE
Rapid battery drain when playing music with data connection

### ISSUE THREAD

**Issue by skinien** [slayher/CM7_Mecha_issue#13]
While playing music with a 3g/4g data enabled, playing music (mp3s off of the SD Card) seems to accelerate battery drain.  On average, the drain is 20%/hr.  This issue seems to be independent of which music player is being used as the accelerated drain occurs with three music players that I've tested: 1) Stock Music app 2) WinAmp 3) PowerAmp (trial).

While playing music WITHOUT 3g/4g data (on Wifi or data disabled), battery drain is similar to when the the phone is on standby, ~2 - 3 %/hr.

**Comment by Jewremy** [comment]
I can confirm this.  Happening to me too.

**Comment by skinien** [comment]
Jewremy, does your phone run hot during this drain?  Mine does.

**Comment by Jewremy** [comment]
it's always in the car dock, so yes.  while it's idling, screen on in the dock it charges, albeit slowly.  while playing music, it'll stay at one level or lose power if I'm playing and navigating at the same time.

**Comment by skinien** [comment]
Similar for me.  I use a car charger and the battery just stays at one level while playing music.

I vaguely remember that RC 1.2 had no issues with battery drain while playing music.  I could go 20 - 30 minutes on bluetooth and lose 3 - 4%.

**Comment by Jewremy** [comment]
Do you have dsp enabled at all?

Also, does your car dock set the volume at a wicked low line level?  As in
volume keys don't do anything.
On Aug 24, 2011 8:27 PM, "skinien" <
reply@reply.github.com>
wrote:

**Comment by skinien** [comment]
Sorry, I didn't make my self clear.  I don't use a dock, I just use a car charger.

DSP is NOT enabled.

I use bluetooth with my car stereo.  I turn the media volume all the way up on my phone so the sound is clearer (rather than keeping the volume low on my phone and turning it all the way up on my stereo).  I'm pretty sure using BT/dock isn't the issue though.  I get the same drain when just using headphones or playing through the speaker.

**Comment by Jewremy** [comment]
Aah.  Okay.  Just another issue...maybe stock function.  I have DSP enabled
and always use the car dock.
On Aug 24, 2011 8:37 PM, "skinien" <
reply@reply.github.com>
wrote:

**Comment by skinien** [comment]
Hey Jewremy, what music playing apps do you have installed (including streaming apps)?  I wonder if one is misbehaving if it can sense that another is playing music.  If we have common apps, I may try to delete it/them.

For me:
-Pandora
-Winamp
-Music
-Amazon mp3

**Comment by skinien** [comment]
Problem solved.

WinAmp was the culprit.  Even if I was using the stock music player, I was getting rapid drain because WinAmp was installed and doing something in the background when I was playing music.  I have deleted it and now everything is back to normal.  

Sorry to report a false CM bug.
