### ISSUE TITLE
SMS issue on "LTE Only"

### ISSUE THREAD

**Issue by m33p** [slayher/CM7_Mecha_issue#14]
when you set the phone to "LTE only" and send a SMS the messaging app reports failure even though the text does make it out..
To reproduce set your phone to "LTE only" then send a text to your self in the AOSP messaging app. You will notice it will still say "Sending" even tho you have already received the text.

**Comment by slayher** [comment]
Honestly you should not be using LTE only.  If you notice the stock firmware doesn't allow for LTE only unless you enter the testing mode of the phone app.  The reason for this is VZW does not officially support VoIP yet.  LTE is data only at this time.
