### ISSUE TITLE
CM7 Thunderbolt RC1.7 BlueTooth Issue

### ISSUE THREAD

**Issue by a1exus** [slayher/CM7_Mecha_issue#26]
I'm trying out CyanogenMod and I gotta say by far this is the best ROM out there, so big thanks for slayher (and anyone else) who was part of porting it to Thunderbolt!

_BIG_ THANKS!!!

So far, I've only encounter 1 issue and I can't call it major but it's pretty important for a lot of folks, so I can't call it minor either...

I paired my phone w/ my car (no problem).
I place _outgoing_ call and I can't hear any sound at all.
Yet when someone calls me I'm able to hear/speak just fine.

I did wipe my /cache /data partition, so it was clean install

If you could look into that, a lot of us would appreciate that:)
Thanks again for all your work and time that you spend on this!

**Comment by AARtwo** [comment]
I think this issue was reported in https://github.com/slayher/CM7_Mecha_issue/issues/19 :).

**Comment by a1exus** [comment]
right, this is same issue...
