### ISSUE TITLE
SMS time stamp

### ISSUE THREAD

**Issue by bobblah** [slayher/CM7_Mecha_issue#4]
With SMS time stamp set to when received, after midnight of that day the time stamp disappears and you are left with just the date for any messages prior to the current day.

**Comment by miketoasty** [comment]
I don't think this is an issue. I believe this is how the AOSP messaging works.

**Comment by DizzyThermal** [comment]
afaik, miketoasty is right.. If the timestamp does not correspond to the current day, it gets rid of the time information and just leaves the day information..
